import './globals.css'; // Import global styles

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* You might want to add Tailwind classes to body if needed, e.g., for dark mode default bg */}
      <body>{children}</body>
    </html>
  )
}
